#! /usr/bin/env python
import os, re
import Task, TaskGen
from TaskGen import extension, declare_extension
from waf_dynamo import new_copy_task


def set_options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(
        features    = 'cc cxx cprogram',
        uselib      = 'DLIB LUA CARES',
        uselib_local= 'script_debug',
        includes    = '../build .',
        target      = 'savefiledump',
        source      = 'savefiledump.cpp stubs.cpp')
